// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.1
// source: agentero/resources/protos/policy_holder.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyHolder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MobileNumber    string             `protobuf:"bytes,2,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	InsurancePolicy []*InsurancePolicy `protobuf:"bytes,3,rep,name=insurance_policy,json=insurancePolicy,proto3" json:"insurance_policy,omitempty"`
}

func (x *PolicyHolder) Reset() {
	*x = PolicyHolder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyHolder) ProtoMessage() {}

func (x *PolicyHolder) ProtoReflect() protoreflect.Message {
	mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyHolder.ProtoReflect.Descriptor instead.
func (*PolicyHolder) Descriptor() ([]byte, []int) {
	return file_agentero_resources_protos_policy_holder_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyHolder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyHolder) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *PolicyHolder) GetInsurancePolicy() []*InsurancePolicy {
	if x != nil {
		return x.InsurancePolicy
	}
	return nil
}

type InsurancePolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MobileNumber string `protobuf:"bytes,1,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	Premium      int32  `protobuf:"varint,2,opt,name=premium,proto3" json:"premium,omitempty"`
	Type         string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *InsurancePolicy) Reset() {
	*x = InsurancePolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsurancePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsurancePolicy) ProtoMessage() {}

func (x *InsurancePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsurancePolicy.ProtoReflect.Descriptor instead.
func (*InsurancePolicy) Descriptor() ([]byte, []int) {
	return file_agentero_resources_protos_policy_holder_proto_rawDescGZIP(), []int{1}
}

func (x *InsurancePolicy) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *InsurancePolicy) GetPremium() int32 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *InsurancePolicy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetContactAndPoliciesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsuranceAgentId string `protobuf:"bytes,1,opt,name=insuranceAgentId,proto3" json:"insuranceAgentId,omitempty"`
}

func (x *GetContactAndPoliciesByIdRequest) Reset() {
	*x = GetContactAndPoliciesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactAndPoliciesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactAndPoliciesByIdRequest) ProtoMessage() {}

func (x *GetContactAndPoliciesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactAndPoliciesByIdRequest.ProtoReflect.Descriptor instead.
func (*GetContactAndPoliciesByIdRequest) Descriptor() ([]byte, []int) {
	return file_agentero_resources_protos_policy_holder_proto_rawDescGZIP(), []int{2}
}

func (x *GetContactAndPoliciesByIdRequest) GetInsuranceAgentId() string {
	if x != nil {
		return x.InsuranceAgentId
	}
	return ""
}

type GetContactAndPoliciesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyHolders []*PolicyHolder `protobuf:"bytes,1,rep,name=policy_holders,json=policyHolders,proto3" json:"policy_holders,omitempty"`
}

func (x *GetContactAndPoliciesByIdResponse) Reset() {
	*x = GetContactAndPoliciesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactAndPoliciesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactAndPoliciesByIdResponse) ProtoMessage() {}

func (x *GetContactAndPoliciesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactAndPoliciesByIdResponse.ProtoReflect.Descriptor instead.
func (*GetContactAndPoliciesByIdResponse) Descriptor() ([]byte, []int) {
	return file_agentero_resources_protos_policy_holder_proto_rawDescGZIP(), []int{3}
}

func (x *GetContactAndPoliciesByIdResponse) GetPolicyHolders() []*PolicyHolder {
	if x != nil {
		return x.PolicyHolders
	}
	return nil
}

type GetContactsAndPoliciesByMobileNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MobileNumber string `protobuf:"bytes,1,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
}

func (x *GetContactsAndPoliciesByMobileNumberRequest) Reset() {
	*x = GetContactsAndPoliciesByMobileNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactsAndPoliciesByMobileNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactsAndPoliciesByMobileNumberRequest) ProtoMessage() {}

func (x *GetContactsAndPoliciesByMobileNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactsAndPoliciesByMobileNumberRequest.ProtoReflect.Descriptor instead.
func (*GetContactsAndPoliciesByMobileNumberRequest) Descriptor() ([]byte, []int) {
	return file_agentero_resources_protos_policy_holder_proto_rawDescGZIP(), []int{4}
}

func (x *GetContactsAndPoliciesByMobileNumberRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

type GetContactsAndPoliciesByMobileNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyHolder *PolicyHolder `protobuf:"bytes,1,opt,name=policy_holder,json=policyHolder,proto3" json:"policy_holder,omitempty"`
}

func (x *GetContactsAndPoliciesByMobileNumberResponse) Reset() {
	*x = GetContactsAndPoliciesByMobileNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactsAndPoliciesByMobileNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactsAndPoliciesByMobileNumberResponse) ProtoMessage() {}

func (x *GetContactsAndPoliciesByMobileNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentero_resources_protos_policy_holder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactsAndPoliciesByMobileNumberResponse.ProtoReflect.Descriptor instead.
func (*GetContactsAndPoliciesByMobileNumberResponse) Descriptor() ([]byte, []int) {
	return file_agentero_resources_protos_policy_holder_proto_rawDescGZIP(), []int{5}
}

func (x *GetContactsAndPoliciesByMobileNumberResponse) GetPolicyHolder() *PolicyHolder {
	if x != nil {
		return x.PolicyHolder
	}
	return nil
}

var File_agentero_resources_protos_policy_holder_proto protoreflect.FileDescriptor

var file_agentero_resources_protos_policy_holder_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x92,
	0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x75,
	0x72, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x2e, 0x49, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x52, 0x0f, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x22, 0x64, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x65, 0x6d, 0x69, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72,
	0x65, 0x6d, 0x69, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x20, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x10, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e,
	0x63, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x21, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42,
	0x0a, 0x0e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x52, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x22, 0x52, 0x0a, 0x2b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x73, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x42, 0x79, 0x4d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x70, 0x0a, 0x2c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x0c, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x32, 0xbd, 0x02, 0x0a, 0x14, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x80, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x2f, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x30, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0xa1, 0x01, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x42,
	0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x3a, 0x2e,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3b, 0x2e, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x73, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agentero_resources_protos_policy_holder_proto_rawDescOnce sync.Once
	file_agentero_resources_protos_policy_holder_proto_rawDescData = file_agentero_resources_protos_policy_holder_proto_rawDesc
)

func file_agentero_resources_protos_policy_holder_proto_rawDescGZIP() []byte {
	file_agentero_resources_protos_policy_holder_proto_rawDescOnce.Do(func() {
		file_agentero_resources_protos_policy_holder_proto_rawDescData = protoimpl.X.CompressGZIP(file_agentero_resources_protos_policy_holder_proto_rawDescData)
	})
	return file_agentero_resources_protos_policy_holder_proto_rawDescData
}

var file_agentero_resources_protos_policy_holder_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agentero_resources_protos_policy_holder_proto_goTypes = []interface{}{
	(*PolicyHolder)(nil),                                 // 0: policy_holder.PolicyHolder
	(*InsurancePolicy)(nil),                              // 1: policy_holder.InsurancePolicy
	(*GetContactAndPoliciesByIdRequest)(nil),             // 2: policy_holder.GetContactAndPoliciesByIdRequest
	(*GetContactAndPoliciesByIdResponse)(nil),            // 3: policy_holder.GetContactAndPoliciesByIdResponse
	(*GetContactsAndPoliciesByMobileNumberRequest)(nil),  // 4: policy_holder.GetContactsAndPoliciesByMobileNumberRequest
	(*GetContactsAndPoliciesByMobileNumberResponse)(nil), // 5: policy_holder.GetContactsAndPoliciesByMobileNumberResponse
}
var file_agentero_resources_protos_policy_holder_proto_depIdxs = []int32{
	1, // 0: policy_holder.PolicyHolder.insurance_policy:type_name -> policy_holder.InsurancePolicy
	0, // 1: policy_holder.GetContactAndPoliciesByIdResponse.policy_holders:type_name -> policy_holder.PolicyHolder
	0, // 2: policy_holder.GetContactsAndPoliciesByMobileNumberResponse.policy_holder:type_name -> policy_holder.PolicyHolder
	2, // 3: policy_holder.PolicyHoldersService.GetContactAndPoliciesById:input_type -> policy_holder.GetContactAndPoliciesByIdRequest
	4, // 4: policy_holder.PolicyHoldersService.GetContactsAndPoliciesByMobileNumber:input_type -> policy_holder.GetContactsAndPoliciesByMobileNumberRequest
	3, // 5: policy_holder.PolicyHoldersService.GetContactAndPoliciesById:output_type -> policy_holder.GetContactAndPoliciesByIdResponse
	5, // 6: policy_holder.PolicyHoldersService.GetContactsAndPoliciesByMobileNumber:output_type -> policy_holder.GetContactsAndPoliciesByMobileNumberResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agentero_resources_protos_policy_holder_proto_init() }
func file_agentero_resources_protos_policy_holder_proto_init() {
	if File_agentero_resources_protos_policy_holder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agentero_resources_protos_policy_holder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyHolder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentero_resources_protos_policy_holder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsurancePolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentero_resources_protos_policy_holder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactAndPoliciesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentero_resources_protos_policy_holder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactAndPoliciesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentero_resources_protos_policy_holder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactsAndPoliciesByMobileNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentero_resources_protos_policy_holder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactsAndPoliciesByMobileNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agentero_resources_protos_policy_holder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentero_resources_protos_policy_holder_proto_goTypes,
		DependencyIndexes: file_agentero_resources_protos_policy_holder_proto_depIdxs,
		MessageInfos:      file_agentero_resources_protos_policy_holder_proto_msgTypes,
	}.Build()
	File_agentero_resources_protos_policy_holder_proto = out.File
	file_agentero_resources_protos_policy_holder_proto_rawDesc = nil
	file_agentero_resources_protos_policy_holder_proto_goTypes = nil
	file_agentero_resources_protos_policy_holder_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PolicyHoldersServiceClient is the client API for PolicyHoldersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolicyHoldersServiceClient interface {
	GetContactAndPoliciesById(ctx context.Context, in *GetContactAndPoliciesByIdRequest, opts ...grpc.CallOption) (*GetContactAndPoliciesByIdResponse, error)
	GetContactsAndPoliciesByMobileNumber(ctx context.Context, in *GetContactsAndPoliciesByMobileNumberRequest, opts ...grpc.CallOption) (*GetContactsAndPoliciesByMobileNumberResponse, error)
}

type policyHoldersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyHoldersServiceClient(cc grpc.ClientConnInterface) PolicyHoldersServiceClient {
	return &policyHoldersServiceClient{cc}
}

func (c *policyHoldersServiceClient) GetContactAndPoliciesById(ctx context.Context, in *GetContactAndPoliciesByIdRequest, opts ...grpc.CallOption) (*GetContactAndPoliciesByIdResponse, error) {
	out := new(GetContactAndPoliciesByIdResponse)
	err := c.cc.Invoke(ctx, "/policy_holder.PolicyHoldersService/GetContactAndPoliciesById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyHoldersServiceClient) GetContactsAndPoliciesByMobileNumber(ctx context.Context, in *GetContactsAndPoliciesByMobileNumberRequest, opts ...grpc.CallOption) (*GetContactsAndPoliciesByMobileNumberResponse, error) {
	out := new(GetContactsAndPoliciesByMobileNumberResponse)
	err := c.cc.Invoke(ctx, "/policy_holder.PolicyHoldersService/GetContactsAndPoliciesByMobileNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyHoldersServiceServer is the server API for PolicyHoldersService service.
type PolicyHoldersServiceServer interface {
	GetContactAndPoliciesById(context.Context, *GetContactAndPoliciesByIdRequest) (*GetContactAndPoliciesByIdResponse, error)
	GetContactsAndPoliciesByMobileNumber(context.Context, *GetContactsAndPoliciesByMobileNumberRequest) (*GetContactsAndPoliciesByMobileNumberResponse, error)
}

// UnimplementedPolicyHoldersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPolicyHoldersServiceServer struct {
}

func (*UnimplementedPolicyHoldersServiceServer) GetContactAndPoliciesById(context.Context, *GetContactAndPoliciesByIdRequest) (*GetContactAndPoliciesByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactAndPoliciesById not implemented")
}
func (*UnimplementedPolicyHoldersServiceServer) GetContactsAndPoliciesByMobileNumber(context.Context, *GetContactsAndPoliciesByMobileNumberRequest) (*GetContactsAndPoliciesByMobileNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactsAndPoliciesByMobileNumber not implemented")
}

func RegisterPolicyHoldersServiceServer(s *grpc.Server, srv PolicyHoldersServiceServer) {
	s.RegisterService(&_PolicyHoldersService_serviceDesc, srv)
}

func _PolicyHoldersService_GetContactAndPoliciesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactAndPoliciesByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyHoldersServiceServer).GetContactAndPoliciesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/policy_holder.PolicyHoldersService/GetContactAndPoliciesById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyHoldersServiceServer).GetContactAndPoliciesById(ctx, req.(*GetContactAndPoliciesByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyHoldersService_GetContactsAndPoliciesByMobileNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsAndPoliciesByMobileNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyHoldersServiceServer).GetContactsAndPoliciesByMobileNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/policy_holder.PolicyHoldersService/GetContactsAndPoliciesByMobileNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyHoldersServiceServer).GetContactsAndPoliciesByMobileNumber(ctx, req.(*GetContactsAndPoliciesByMobileNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolicyHoldersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "policy_holder.PolicyHoldersService",
	HandlerType: (*PolicyHoldersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContactAndPoliciesById",
			Handler:    _PolicyHoldersService_GetContactAndPoliciesById_Handler,
		},
		{
			MethodName: "GetContactsAndPoliciesByMobileNumber",
			Handler:    _PolicyHoldersService_GetContactsAndPoliciesByMobileNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentero/resources/protos/policy_holder.proto",
}
